### ISSUE TITLE
Doesn't appear work with iOS8

### ISSUE THREAD

**Issue by hollyschinsky** [ccoenraets/PageSlider#12]
There appears to be an issue in iOS8 with the slidePage() function. The app shows a blank screen if you call something like: slider.slidePage(new HomeView(service).render().$el); The same app runs fine in iOS7. If you put text in the index.html and comment out the slidePage it will display the text. Continuing testing.

**Comment by hollyschinsky** [comment]
Note, the problem appears to be with the webkit translate 3d. If you change it to use 1px at the end such as: -webkit-transform: translate3d(100%, 0, 1px); for all of the webkit-transform-translate3d values for the page, page.right, page.left, page.center then it seems to fix it.  

http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d

**Comment by sanbeaman** [comment]
I've tried hollyschinsky's solutio, but I  continue to get a blank screen when emulating for ios.  
I've been going thru a number of Christophe Coenraets excellent cordova- ....  backbone ... requirejs, etc.. projects  and in every case I've had to remove the slider.slidePage() and revert to $('body').html().

maybe it's my xCode? or ios sim... but can't figure out how to leverage the pageSlider going forward

**Comment by hollyschinsky** [comment]
Hey drewbe, here's the fix that worked for me: https://github.com/hollyschinsky/phonegap-workshop/blob/master/www13/assets/css/pageslider-fix.css

I know you tried the solution, but just in case it's helpful to have the actual file that worked for me... :)

**Comment by sudham** [comment]
I installed the app on android - does not do anything. Is there any test app that goes with this lib for android ?

**Comment by fortiko** [comment]
Using the file pageslider-fix.css indicated above works: please update this for iOS8!

**Comment by amytych** [comment]
Thanks @hollyschinsky, helped mi also!

:+1: for PR for this change

**Comment by ccoenraets** [comment]
Added CSS fix. Thanks Holly.

**Comment by JakeBernstein65** [comment]
Worked! Thanks Holly

**Comment by timrobertson0122** [comment]
:+1: Holly, thanks!
